apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: web          # étiquette réutilisée par les ReplicaSets/Services
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
